# Generated by Django 5.2.1 on 2025-05-19 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='can_be_contacted',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='can_data_be_shared',
            field=models.BooleanField(default=True),
        ),
    ]
