# Generated by Django 5.2.1 on 2025-05-19 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='date_joined',
            new_name='time_created',
        ),
    ]
