# Generated by Django 5.2.1 on 2025-05-29 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_issue_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='progress',
            field=models.IntegerField(choices=[(1, 'To do'), (2, 'In progress'), (3, 'Finished')], default=1),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issue_type',
            field=models.IntegerField(choices=[(1, 'BUG'), (2, 'FEATURE'), (3, 'TASK')], default=3),
        ),
    ]
