# Generated by Django 5.2.1 on 2025-06-05 08:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_alter_issue_assigned_to'),
        ('users', '0003_alter_user_age_alter_user_can_be_contacted_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contributors',
            field=models.ManyToManyField(related_name='contributed_projects', through='users.Contributor', to=settings.AUTH_USER_MODEL),
        ),
    ]
