# Generated by Django 5.2.1 on 2025-06-05 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0008_project_contributors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='contributors',
        ),
    ]
